add cmds and soft deleteion
filecoin-project/venus-auth pull request #64
Opened 2021-11-23 08:43 UTC by simlecode

1. add cmds: delete user and get token
2. using soft deleteion (`user` and `token`)

2022-05-07 07:40 UTC, zl03jsj commented
igtm

2022-05-19 03:08 UTC, zl03jsj requested changes
此处应该对`resp.StatusCode`做相应的错误处理.

2022-05-19 03:53 UTC, zl03jsj requested changes

2022-05-19 03:53 UTC, zl03jsj commented on cmd/jwtclient/auth_client.go
> +	return false, nil
此处应该对`resp.StatusCode`做相应的错误处理.

2022-05-19 03:53 UTC, zl03jsj commented on storage/badger.go
> +		user.setDeleted()
建议这里增加判断
```go
if user.isDeleted() {
// 如果已经是删除状态, 则不用做后面的所有操作.
}
```

2022-05-19 03:53 UTC, zl03jsj commented on storage/badger_helper.go
> +		}
这里做这样的修改是否方便:
在`softDelete`中增加`isDelete`, 当isDelete时, 直接返回就行了

2022-05-19 03:53 UTC, zl03jsj commented on storage/mysql.go
> +	err := s.db.Transaction(func(tx *gorm.DB) error {
这个事务看起来有点怪啊..
看起来是在一个事务里面, 但里面所有的操作, 貌似都是用的不同的session来执行的. 
并且这个`tx`作为参数, 也没有发挥任何作用.

2022-05-19 03:53 UTC, zl03jsj commented on storage/mysql.go
> +	if err := s.db.Table("miners").Debug().Where("miner = ? and deleted_at is NULL", storedAddress(maddr)).Count(&count).Error; err != nil {
这个`Debug()`是调试是加上的吗?

2022-05-19 04:12 UTC, zl03jsj commented on storage/mysql.go
> +		log.Infof("delete user %s, delete miners %v", userName, addrs)
这个事务看起来有点怪啊..
看起来是在一个事务里面, 但里面所有的操作, 貌似都是用的不同的session来执行的. 
并且这个`tx`作为参数, 也没有发挥任何作用.

2022-05-19 04:14 UTC, zl03jsj requested changes

2022-05-19 04:14 UTC, zl03jsj commented on storage/mysql.go
> +	})
这个事务看起来有点奇怪啊.
其中的所有数据库操作都使用的不同的session, 并且这个`tx`作为参数, 没有任何的作用.

2022-05-19 08:28 UTC, simlecode commented on cmd/jwtclient/auth_client.go
> +	return false, nil
fixed

2022-05-19 08:28 UTC, simlecode commented on storage/badger.go
> +		user.setDeleted()
fixed

2022-05-19 08:28 UTC, simlecode commented on storage/badger_helper.go
> +		}
fixed

2022-05-19 08:29 UTC, simlecode commented on storage/mysql.go
> +	if err := s.db.Table("miners").Debug().Where("miner = ? and deleted_at is NULL", storedAddress(maddr)).Count(&count).Error; err != nil {
是的，已删除

2022-05-19 08:29 UTC, simlecode commented on storage/mysql.go
> +	})
fixed

2022-05-19 08:55 UTC, zl03jsj commented
@simlecode

关于DeleteUser的实现我稍微修改了一下:
增加了:
innerGetUser, innerListMiners, innerDelMiner, 

主要原因是:
1, 代码重用
2,在将相关逻辑变化的时候, 只需要修改`innerXXXX`函数的实现就可以 了. 如果每个地方单独实现, 很有可能就会遗漏掉.

请检查提交:
https://github.com/filecoin-project/venus-auth/pull/64/commits/c58c77db113fbd74343c915008598df9ec063329

2022-05-19 09:08 UTC, zl03jsj approved these changes

2022-05-19 09:10 UTC, zl03jsj commented
我这里感觉没有问题了, 请@hunjixin review

2022-05-20 01:13 UTC, hunjixin approved these changes

2022-05-20 02:06 UTC, merged